### ISSUE TITLE
Loop doesn't work seamlessly

### ISSUE THREAD

**Issue by songproducer** [kyouryuukunn/renpy-ActionEditor#4]
>$ camera_moves( ( (1500, 0, 0, 0, 5, 'linear'), (-1500, 0, 0, 0, 10, 'linear') ), loop=True)

It jumps a few pixels forward when ending the loop

**Comment by kyouryuukunn** [comment]
A Seemlessly Loop needs that the camera position of start and end  is same.

IF the camera start position is (0,0,0,0)
`$ camera_moves( ( (1500, 0, 0, 0, 5, 'linear'), (-1500, 0, 0, 0, 15, 'linear'), (0, 0, 0, 0, 20, 'linear')), loop=True)`

**Comment by songproducer** [comment]
Thanks!
